### ISSUE TITLE
Availability for prototype presentation on Wednesday 13th Dec

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#1]
Hey @kellygrellier!
We would love to show you the final product next wednesday. 
Please let us know when you're available? This can be done in person or remotely. 
Thanks!

**Comment by kellygrellier** [comment]
Hi I have availability all day next Weds and would love to do it in person if possible.  Thanks, Kelly

**Comment by Jen-Harris** [comment]
Looking forward to catching up at 11!

**Comment by kellygrellier** [comment]
Can't wait!
