### ISSUE TITLE
Content needed!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#105]
Hey @kellygrellier, 

Hope you're having a good week. We're making great progress with the sprint 👍 

There's a couple of things we still need from you if possible: 
* examples of Good & Bad photos 
* A list for the reasons for rehoming question
* Please let us know what you think of the desktop designs!

**Comment by kellygrellier** [comment]
[Reasons for giving up a pet.docx](https://github.com/InFact-coop/BlueCross/files/1772221/Reasons.for.giving.up.a.pet.docx)

Hi Jen, Sorry I have been off site & then catching up today...attached is a document with primary & secondary reasons for giving up a pet.

**Comment by kellygrellier** [comment]
I have asked Mandy for the photos - hopefully she will send them tomorrow..I will have a look at the site design now :-)

**Comment by kellygrellier** [comment]
![good pic 1](https://user-images.githubusercontent.com/34315717/36891654-4514f96e-1dfa-11e8-991b-ba0e851312c9.JPG)
![good pic 2](https://user-images.githubusercontent.com/34315717/36891655-4530d7ba-1dfa-11e8-9263-3e254dc2286a.jpg)
![good pic 3](https://user-images.githubusercontent.com/34315717/36891656-4544432c-1dfa-11e8-8239-d7363093f399.jpg)
![bad pic 1](https://user-images.githubusercontent.com/34315717/36891657-4559d80e-1dfa-11e8-8b8a-94f2efb253f2.JPG)
![bad pic 2](https://user-images.githubusercontent.com/34315717/36891658-4573979e-1dfa-11e8-9296-5a85b438c0fb.JPG)
![bad pic 3](https://user-images.githubusercontent.com/34315717/36891660-458e9be8-1dfa-11e8-89eb-130a5d7c9ee8.JPG)

**Comment by kellygrellier** [comment]
1st 3 are good pics, last 3 are bad pics (too far/blurred/can't see the dog very well)

**Comment by Jen-Harris** [comment]
Such a cutie!! Do you want all 3 of each or just 1 of each?

**Comment by kellygrellier** [comment]
Hi Jen,

Perhaps just one of each - I was thinking so they feel more accessible, the indoor good one with her ball and the indoor bad one unwrapping presents?

Do you agree?

Thanks, Kelly

**Comment by Jen-Harris** [comment]
Perfect, we will use those. 🐶
