### ISSUE TITLE
Thank-you page text

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#111]
Hi @Jen-Harris,

Would it be possible to change the text for the thank-you page slightly and include a link to our pet bereavement support service? as follows:

"We will be in touch within 2 days to arrange a time to come and see you and 'name of dog', when we will plan his rehoming journey and any further support you need.  

We know saying goodbye to a much loved pet is hard, if you need somebody to talk to, details of our confidential Pet Bereavement Support Service can be found here."

Would it be possible to make here a link to:
https://www.bluecross.org.uk/pet-bereavement-and-pet-loss

Thanks, Kelly

**Comment by Jen-Harris** [comment]
No problem @kellygrellier, we can definitely add this!
