### ISSUE TITLE
Privacy & Cookie Policy

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#118]
Hi @Jen-Harris,

Is it possible as well as a link to the terms of service at the bottom of the pages that we have a link to: 

'Blue Cross Privacy & Cookie policy'

With the text as above lining to the below link?

https://www.bluecross.org.uk/privacy-and-cookie-policy

Thanks very much!  This is linked to the GDPR statement.

Thanks, Kelly

**Comment by Jen-Harris** [comment]
No problem!
