### ISSUE TITLE
Google Analytics & scroll bar issue

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#145]
Hi @Jen-Harris and @maxgerber,

It was great to see you today and thank-you very much!  I meant to ask you about Google Analytics, did you manage to set it up on the site?

Also I was just looking through the site again on my laptop and noticed there is no scroll bar so it can be difficult to scroll down if you haven't clicked away from an option, is it possible to fix this?

Thanks, Kelly

**Comment by maxgerber** [comment]
Hi @kellygrellier,
I have set up google analytics for you, but it needs a google account for me to be able to give access to you. Do you either have one, or are able to set one up, after which I'll take care of the rest?

Thanks,
Max

**Comment by kellygrellier** [comment]
Hi Max,
I do have a google account: my email is kellygrellier.kg@gmail.com, will that be okay?

Thanks, kelly

**Comment by maxgerber** [comment]
Hi Kelly,
I've just added you via that address - now you should be able to login to analytics.google.com - let me know if that works!

Max

**Comment by kellygrellier** [comment]
Hi @Maxgerber

Will I receive an invite from you to google analytics?

Thanks, Kelly

**Comment by maxgerber** [comment]
I don't think you'll need an invite, you should be able to just login and get full access!

**Comment by kellygrellier** [comment]
Hi @Max,

It works thanks :-)
