### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#152]
Hi @Jen-Harris and @maxgerber 
I have noticed that you have to actively click away after completing an action in order to be able to scroll properly using down arrows.  For example of the page with dogs likes dislikes, if you don't scroll away the paw keeps moving up the scroll bar.  or if you scroll down on a page where you make a selection (like breed) if you don't click away after and try to move down the page then the selection changes but you don't move.
Are you able to fix this?  

Thanks, Kelly

**Comment by Jen-Harris** [comment]
Hey @kellygrellier, 
With the sliders this is to be expected as they are input fields so you will always have to click away. 
In terms of the rest of the site we don't know why this is, we will have a look at why this may be but we may not be able to get this in place

**Comment by kellygrellier** [comment]
Thanks Jen, I am sure people will work it out and click away :-)
