### ISSUE TITLE
Questions in pdf 

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#16]
[Questions and logic.pdf](https://github.com/InFact-coop/BlueCross/files/1539860/Questions.and.logic.pdf)

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
[Questions and logic.pdf](https://github.com/InFact-coop/BlueCross/files/1539865/Questions.and.logic.pdf)
I have written out the questions and logic....the last pages didn't scan well so I will re do them.

**Comment by Jen-Harris** [comment]
This is great, thank you @kellygrellier ! Really helpful!
