### ISSUE TITLE
Additional Internal Email Recipients from Heroku

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#170]
Hi @maxgerber,

Is it possible to have additional internal email recipients with Heroku?  I would like our analyst to receive the output as well, as she will be putting the info into a spreadsheet for analysis?

I hope its all going well, the site is looking great!

**Comment by maxgerber** [comment]
Hi @kellygrellier,
I've just had a look at that section of the codebase and I'm happy to put this in the scope. Do you have the emails to hand?

Best,
Max
