### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/BlueCross#171]
Hi @kellygrellier,
So one of my colleagues is working on our new infact website currently, and has asked if there were any people I could think of who might be up for writing a short quote/testimonial about the (hopefully) positive experience of working with us. Naturally I thought of you - is this something you might be interested in?

**Comment by kellygrellier** [comment]
Hi @maxgerber 
Hi Max, I would absolutely be very happy to leave a testimonial - how many words should it be?

Thanks, Kelly

**Comment by maxgerber** [comment]
@kellygrellier Thanks for that, your testimonial is perfect - I'm blushing! :)

We'll let you know when our new site is live (and will of course link back to you guys)
