### ISSUE TITLE
New GDPR Statement

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#175]
Hi @maxgerber 
[5 Rehoming (V2 with 'also').docx](https://github.com/InFact-coop/BlueCross/files/2039038/5.Rehoming.V2.with.also.docx)

**Comment by kellygrellier** [comment]
Hi @maxgerber 
I have attached above the revised GDPR statement, It is slightly different as it doesn’t have SMS ( we don’t have a marketing programme with SMS at the moment) It also has mail opt out .  
I hope this is okay to do?
Thanks again, Kelly

**Comment by maxgerber** [comment]
Hi @kellygrellier,
I've updated the GDPR-ish section of Owner Info to this document to include the copy you sent over in that doc, However, I've left out a couple of things that I wanted to run by you first.

1. Revising the style of the checkboxes to be "**yes**"/"**no**" is actually slightly more involved than a copy change, as it involves hooking the new data up throughout the app to the email. I won't be able to get that done before the end of the day, but I can look into doing it next week.

2. The new "post" checkbox utilises an "opt-out" design pattern. This is generally not recommended under GDPR; it is considered preferable to offer users "opt-in" consent. [This is a link from the Information Commisoner's Office](https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/consent/) which explains this in further detail.
<img width="1036" alt="screen shot 2018-05-25 at 1 46 24 pm" src="https://user-images.githubusercontent.com/22657280/40546424-27188a9c-6027-11e8-8163-699694ba2bbf.png">

This is how it currently looks (though I haven't pushed it up yet) - please let me know your thoughts!

Max

**Comment by kellygrellier** [comment]
Hi @maxgerber 
I am happy with how you have put it above and agree with you in terms of the opt in point.  Don't worry about the yes /no I think it is fine as you have put it.  Could we get rid of the text option though?

Thanks, Kelly

**Comment by maxgerber** [comment]
Hi @kellygrellier,

That's perfect - I have removed the text option and will merge in the changes now! You should be able to see the updated version live in the next couple of hours.

Over and out,

Max
