### ISSUE TITLE
Kelly Response to designs

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#18]
Hi @Jen-Harris 
 It is looking amazing!
1.We thought following just dog for skateboard is a good idea too.
 Flow & Questions:
2.Giving a pet - we were thinking Find a new home for my pet I really like the description you have put underneath.
3.Next we thought What is your pet (and like you say just follow dog flow)
4.Then we thought it would be neat to ask them what the name is of their dog so we can then populate the questions with the name of their pet so it is personalised.
5.Then we thought we could find out the urgency - I really like how you have illustrated this the only change I would make is rather than under one week put 2- 3 weeks (if they put urgently it would be good to have a pop up that says we will be in touch within 24 hrs)
6.Then into about your pet, we have tried to keep the basic info to a minimum as follows:
 Breed (we will give you a drop down menu)
 Male / Female
 Is 'Rex' Microchipped, Neutered, Vaccinated (don't put in wormed)
 When was Rex's last visit to the vets within month/3 months/6 months/1 year/18 months or more
7.On Personality we thought it would be good to give them a whole list of words to check against - this will give us a really good feel for the dogs personality, also we could use it to populate the advert so Rex's owners said he is - and then show a word cloud in the shape of the blue cross logo?
8.Rather than new owners home we thought it would be good to have So we find Rex a home he loves where would he put his paw and then show sliding scales for:
 CATS - love, Lives with, Tolerates, Chases, No thanks!
 CHILDREN - Loves, Okay if they leave me alone, on my terms, No thanks!
 UNFAMILIAR PEOPLE - Loves, in my home, in small numbers, not on my patch, Outside, No Thanks!
9.We thought they could then upload photos & videos
10.I agree about a map and putting in their postcode (this will also allow us to see how far they are from our rehoming centres and how much potential additional support we could provide)
11.We thought we could give them a choice of support as follows:
 A: They chat to prospective owners directly and rehome from home
 B: Rehome from home but Blue Cross help them find owners
 C: Blue Cross look after at their centre and rehome for them
12.Then they provide their details
13.We thought it would be good to have a what happens next based on what they have chosen so:
 If they chose A then 'your advert will appear and you can get started staright away
 If they chose B or C then someone from Blue Cross will be in touch within 24 hrs if they said urgent or 4 working days if they said 2 weeks or more)
 12 We would also like to have a 'Be Safe' button somewhere to provide advice about meeting with people.

The overall design looks spot on, you have captured the Blue Cross Brand perfectly! It would be great if we could get Pets change lives we change theirs somewhere help Rex change someones life for example?

Thanks so much!!

**Comment by Jen-Harris** [comment]
Hey as this is being discuss in issue #8 I will close this one!
