### ISSUE TITLE
Personailty words for owners to choose

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#19]
We thought it would be good for the personality bit to get owners to choose from a list of words the ones that best describe their dog, we could then use it as a word cloud in the advert...
Happy
Playful
Loving
Cuddly
Kind
Caring
Independent
Lively
Naughty
Funny
Jolly
Sensitive
Anxious
Nervous
Grumpy
Scared
Couch potato
Lazy
Active
Energetic
Sleepy
Snoozy
Noisy
Quiet
Calm
Excitable
Crazy
Obedient
Focussed
Distracted
Trained
Silly
Greedy
Frantic
Relaxed
Chilled
Awesome

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
We thought it would be good for the personality bit to get owners to choose from a list of words the ones that best describe their dog, we could then use it as a word cloud in the advert...
 Happy
 Playful
 Loving
 Cuddly
 Kind
 Caring
 Independent
 Lively
 Naughty
 Funny
 Jolly
 Sensitive
 Anxious
 Nervous
 Grumpy
 Scared
 Couch potato
 Lazy
 Active
 Energetic
 Sleepy
 Snoozy
 Noisy
 Quiet
 Calm
 Excitable
 Crazy
 Obedient
 Focussed
 Distracted
 Trained
 Silly
 Greedy
 Frantic
 Relaxed
 Chilled
 Awesome

**Comment by Jen-Harris** [comment]
Hey @kellygrellier, this is great! But possibly a few too many?? Could we reduce the list to between 10-15? 
If this project was to continue into a build sprint we would love to make this a self entry system with autocomplete functionality to help the user decide on words!

**Comment by kellygrellier** [comment]
Hi Jen,

That sounds good!  I will shorten the list 😀

Thanks Kelly

**Comment by kellygrellier** [comment]
Hi @Jen-Harris,
Playful
Nervous
Cuddly 
Greedy
Laid back
Obedient 
Barker
Loving
Energetic 
Grumpy 

Thanks, Kelly

**Comment by Jen-Harris** [comment]
Great! Thank you @kellygrellier
