### ISSUE TITLE
Confirm desired question and triage points for user journey 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#2]
Hey @kellygrellier,
Please let us know what questions you feel are best to include in the prototype and the order in which you would like them? It would also be very useful to know any triage points where the user journey may change (either to continue with different questions or be recommended to call the help line at this stage in the development)
Thanks!

**Comment by kellygrellier** [comment]
Hi Jen,
Just to let you know that I am on the email I am using is actually my personal one as I think the Blue Cross  firewall is blocking it...
Key points in the triage is urgency: I think very early in the journey we should know how quickly they need to give their pet up and if they would rather their pet be rehomed straight from their home or if they would like us to look after it.
Then we will know to reassure them appropriately for their preference.

**Comment by kellygrellier** [comment]
I will get the questions to you today, I am thinking along the lines of:
Q: Urgency
Q: Basic pet info - what kind, breed, age, health
Q: Personality traits (this could be a triage decision point for behaviour intervention)
Q: Likes & Dislikes
Q: Top3 important qualities of the new home & owner

**Comment by kellygrellier** [comment]
[12422 - Brand Guidelines w_new strapline artwork_final_compressed.pdf](https://github.com/InFact-coop/BlueCross/files/1538562/12422.-.Brand.Guidelines.w_new.strapline.artwork_final_compressed.pdf)

**Comment by kellygrellier** [comment]
Morning attached is the Blue Cross Brand Guidelines.
Thanks, Kelly

**Comment by kellygrellier** [comment]
If you need to call me my phone number is:
07917078184

**Comment by kellygrellier** [comment]
Just a thought before going into meetings this morning.....In terms of the information we need, we ultimately need to be able to populate the type of profile we have on our rehome a pet section of our website.  
We don't want to ask them why they are giving it up as it can feel a bit judgmental...
Could we have a catch up this afternoon?

**Comment by Jen-Harris** [comment]
Hey @kellygrellier, sorry for not responding to this issue - think I missed the later comments because I wasn't tagged! 
Hopefully the language we've used help to not feel judgemental but we can review this tomorrow. 
Looking forward to catching up 
Jen
