### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#21]
Hi @Jen-Harris,

Morning Jen,  I am just thinking about getting people who are on Gum Tree/Pre-loved selling older dogs (not puppies as this is too complex for skateboard) to be user testers.  Could you let me know what process we will go through so I know what to say to them?  Or should I ask Noga or Ellie?

Thanks very much, Kelly

**Comment by Jen-Harris** [comment]
Morning @kellygrellier,
__Love__ that you are already thinking about user testing, this is _*amazing*_!
  
There's a few really good resources on user testing: 
-  [Googles Gurilla Testing Advice](https://www.youtube.com/watch?v=0YL0xoSmyZI&feature=youtu.be)
- [Script Guidance and Template](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/user-testing.md#1-planning)
- [Steve Krug user testing script](https://sensible.com/downloads/test-script.pdf)

__The three key points for testing are:__
- Have a script which has tasks for them to complete
- Ask for people to give you a commentary of what they are doing, but don't respond to them
- Document their response in detail! 
- Look for body language etc. as well as what they are saying

The resources are quite detailed so maybe have a look through these and then shout if you have questions?

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
Thanks very much for this :-)

**Comment by Jen-Harris** [comment]
hey @kellygrellier,
@maxgerber and I were chatting to Ellie & Noga yesterday and we thought it would be a good idea if we run through an example of how to run a user test with you tomorrow? We could do a 'demo' of the full flow. 
Do you think this would be helpful?
