### ISSUE TITLE
Are you waiting on me for anything?

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#28]
Hi @Jen-Harris,
Are you waiting for me on anything, I just want to make sure I am looking at the right things and not holding you up!

Thanks, Kelly

**Comment by Jen-Harris** [comment]
You are such a star PO @kellygrellier! 🌟 🌟 🌟 
We have everything we need at the moment! We're writing code now so we'll let you know if that changes and we need input. 
Jen
