### ISSUE TITLE
Mobile vs Desktop

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#3]
Hey @kellygrellier, 
For the prototype it's best for us to focus on a single screen size. Did you imagine the being mobile or desktop first? 
Thanks!

**Comment by kellygrellier** [comment]
I think Mobile, as that is what people use most if that's okay?  Will it be transferable?

**Comment by Jen-Harris** [comment]
Yes either way is transferable! It's just hard to do both in such a short time 👍
