### ISSUE TITLE
Next Monday

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#32]
Hey @kellygrellier, 

Just to let you know we won't be working on Monday as we have another design day. 

We'll have our final build day 10-6 on Tuesday and then the presentation on Wednesday.  👍

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
That sounds great, enjoy your Monday workshop!  What time would you like to meet on Weds and where?

Thanks, Kelly

**Comment by Jen-Harris** [comment]
We're really flexible with timing! Totally up to you. And we're happy to come to you (if you're in London?) or we can do it via hangouts.

**Comment by kellygrellier** [comment]
Great, would you like to meet me at 11 am at our offices next to our Victoria animal hospital? 
Sheppard House, 1-5 Hugh Street, SW1V 1QQ

I can't wait!
Have a great weekend, Kelly

**Comment by Jen-Harris** [comment]
This sounds perfect to us. It gives us some time in the afternoon as well to make any small amends you may want before testing. 
(hopefully we'll get to see some cute pets as well...! 🐶 )
Have a good weekend too
