### ISSUE TITLE
Info in issue1

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#4]
Hi Jen,  Just to let you know I put brand guidelines and some thoughts in response to issue 1.
Thanks, Kelly

**Comment by kellygrellier** [comment]
Hey @Jen-Harris

**Comment by kellygrellier** [comment]
Sorry just getting used to this and realised you won't have been flagged!

**Comment by Jen-Harris** [comment]
Hey @kellygrellier! Thank you!
