### ISSUE TITLE
Feedback from presentation - tweaks!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#44]
🌮 

**Welcome page**
- [x] change time frame from 2-3 weeks to a couple of months

**New home**
- [x] Paw on the slider! 

**Who's looking**
- [x] Add copy to make sure that the title makes sense!

**Video**
- [x] Allow people to move to next page without having too take a video 

**Pet info**
- [x] Take the name from the pet and bring it through the rest of the app 
- [x] More breeds of doggo
- [x] Sex of doggo
- [ ] Refer to a non gendered pet

**Favicon**
- [ ] ~~Add BX favicon! - added favicon asset but can't get it to show 👎~~

**Final page**
- [x] Make sure that the wording is clear for what help they need 
- [x] Include a not sure option 

**thank you**
- [x] Make the time in which they'll be contacted more clear

**Page scrolling**
- [ ] ~~on mobile the screen scrolls past the navbar - can we prevent this? (not an issue on dev tools)~~

**Update readme**
- [x] Include more detailed ideas for next sprint for MVP idea

**Comment by maxgerber** [comment]
@kellygrellier here's the link for the techforgood application if you're interested! https://www.comicrelief.com/your-impact/how-we-make-grants/tech-for-good
