### ISSUE TITLE
Apps like ours...

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#49]
Hi both,

Thanks so much for everything you have done so far!  I thought you would be interested in this app which is American...Tinder for dogs:
https://barkbuddy.com/

Would you let me know when the video bug is fixed and I will get with sharing with Blue Cross and arranging user testing.

Thanks again....

Kelly

**Comment by maxgerber** [comment]
Hi Kelly,
That's hilarious. ( and we thought we had the good ideas ). If someone has denied permission or there's an error with the video, they will be presented with **this view**: 
<img width="370" alt="screen shot 2017-12-20 at 5 08 06 pm" src="https://user-images.githubusercontent.com/22657280/34219255-7f63bc34-e5a8-11e7-9c82-a58542d10c03.png">

Hope this suits, and talk to you in the new year
