### ISSUE TITLE
Catch up later?

### ISSUE THREAD

**Issue by kellygrellier** [InFact-coop/BlueCross#5]
Hi @Jen-Harris 
How is it going?  I am just about to work through some more detail on the questions, would you like to have a catch up this afternoon?

Thanks, Kelly

**Comment by Jen-Harris** [comment]
Hey @kellygrellier,

Are you able to put the questions in the issue for us? That way it is easier for us to refer to? 
We are of course happy to have a call as well if you feel this will help? 

We are currently working on the designs - we'll put these in an issue by 3:30 for you to review!

**Comment by kellygrellier** [comment]
Hi Jen, that's absolutely fine!  I am working on them now :-)
