### ISSUE TITLE
Redesign for app to be desktop compatible 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#86]
- [ ] Update designs on Figma

**Comment by Jen-Harris** [comment]
Hey @kellygrellier! 
As Max mentioned on the phone i've been working on the designs today. This is to bring them inline with going Desktop first and to reflect the changes requested for the Sprint. 
You can see the designs [HERE](https://www.figma.com/file/f8BH9BNgYnLQxRtbnXNmUwTH/Blue-Cross?node-id=13%3A4). 
You have editing rights for this software so if any of the text is wrong please go ahead and edit this. We will refer to these designs when we start coding. 
Please also let me know any feedback you have! 
Jen

**Comment by kellygrellier** [comment]
Hi,

The designs are looking absolutely brilliant!  I love it!  I have made some comments, would you mind letting me know if you can see them?  Thansk, Kelly

**Comment by Jen-Harris** [comment]
Thanks Kelly! Will make the requested changes 👍 🌮

**Comment by Jen-Harris** [comment]
regarding the terms of service - what exactly is this? It could probably go on the main site or this one, whichever you prefer.

**Comment by kellygrellier** [comment]
Hi Jen,
https://www.bluecross.org.uk/terms-and-conditions
This is the link to the Blue Cross website terms & conditions, could we create a link from this site the our main site T&Cs?  I think it will need to be accessible at the bottom of each page.
Thanks, Kelly

**Comment by kellygrellier** [comment]
Sorry not a very well written sentence, I meant to say could we link the site that you are developing to our main site's terms & conditions?
https://www.bluecross.org.uk/terms-and-conditions
