### ISSUE TITLE
Design email template

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#87]
- [x] Design in Figma email to be sent to user 
- [x] Design in Figma email to be sent to BC

**Comment by Jen-Harris** [comment]
Hey @kellygrellier, 

I've quickly mocked up what the emails could look like. For both the user as well as to Blue Cross. At the moment we aren't sure how easy it will be to style these but we're assuming there will be a way! 

I wasn't sure what type of copy etc you would like so please let me know. 

The draft are [HERE](https://www.figma.com/file/f8BH9BNgYnLQxRtbnXNmUwTH/Blue-Cross?node-id=179%3A109)

**Comment by kellygrellier** [comment]
Hi Jen,

It is looking really good, the only thing I think that would be helpful is on the 'New Home' section to stipulate the % as positive, e.g. 57% happy with children.
Thanks, Kelly

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 

It is looking really good, the only thing I think that would be helpful is on the 'New Home' section to stipulate the % as positive, e.g. 57% happy with children.
Thanks, Kelly
